### ISSUE TITLE
Blazor Report Viewer docs to reference SASS themes only

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/reporting-docs#114]
This article must only link the SASS themes https://docs.telerik.com/reporting/blazor-report-viewer - only they are supported with the Telerik Blazor UI components, and adding the LESS themes to the mix will cause issues as people will get two Kendo themes at once.

At worst, if referencing LESS themes is important, a note must be added that if you use the Telerik UI for Blazor components, you must use only one of the SASS themes and register it only once.

This article should also, by default, show an example with a SASS theme (like Default-2) - the snippet in Step 3 - https://docs.telerik.com/reporting/blazor-report-viewer-how-to-use

Reported in this thread https://www.telerik.com/forums/resizing-the-editgridmode-popup#J9Q3hk21MEeiZsKDgGGDqw

**Comment by atkeranov** [comment]
Resolved and the documentation has been reuploaded.
