### ISSUE TITLE
Add explanatory info for SELECT command in our report designers

### ISSUE THREAD

**Issue by ighristov** [telerik/reporting-docs#1398]
The SQL command executed by the Report Designer to fetch the fields schema, is using "ExecuteReader" method. This allows executing harmful SQL that actually deletes tables or drops the database. We cannot restrict the usage to 'select only' queries, so we must explain it in the docs that:
1) the command will be executed as-is, even if it contains delete, update, or drop statements.
2) we strongly recommend to use connections with read-only permissions to fetch the data.

Codebase: Telerik.Reporting.Processing.Data.GetDataReader(IDbCommand command)

SUGGESTION: please check if the old Report DEsigner (like, from 2018) does the same, i.e. it allows dropping a table while in the SqlDataSource wizard.

**Comment by mzanev** [comment]
Tested with the 2013 Q2 version of the Standalone Report Designer and was able to drop a table by executing the select query of the SQL Data Source Wizard.
