### ISSUE TITLE
Update information for Native Angular Report Viewer

### ISSUE THREAD

**Issue by ighristov** [telerik/reporting-docs#1406]
Telerik UI for Angular stopped supporting Angular 13 and 14 with their Q2 release: https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/

Please check our docs and update where needed.

**Comment by DimitarNikolovv06** [comment]
It is now specified in the docs that the minimum support version of Angular for NARV is 15. due to the upgrade to Kendo UI for Angular 16.1.0. This change comes with the Q3 2024 release and will be merged alongside the other changes to the docs for that release.
