### ISSUE TITLE
Breaking change in Reporting Globalization behaviour.

### ISSUE THREAD

**Issue by NikolayYakov** [telerik/reporting-docs#1449]
In the Q3 release, we will introduce a breaking change in the way we resolve culture globalization properties. From now on instead of using the default globalization setting of every specific culture, we will take into account the machine's local settings. 

The fix is related to a change in the default value of en-US culture CurrencyNegativePattern from 0 to 1 which result in negative values displayed like this  **-$100** instead of this **($100)**  in .Net Core.

The change is made in both .Net Framework 4.6.2 and .Net 6.

Related issue: https://github.com/telerik/reporting/issues/2482
Correspondence with Microsoft on the matter:  https://github.com/dotnet/runtime/issues/103644

**Comment by mzanev** [comment]
Resolved with PR: https://github.com/telerik/reporting-docs/pull/1484
